DELETE FROM PRODUCTOS;
SELECT * FROM PRODUCTOS;
INSERT INTO PRODUCTOS (uuid, nombre, peso, precio, descripcion, url_imagen) VALUES
(gen_random_uuid(), 'Teclado Mecánico RGB', 850, 75.50, 'Teclado con switches blue y retroiluminación personalizada.', 'https://i.ibb.co/qLKfzMyd/A0.png'),
(gen_random_uuid(), 'Monitor UltraWide 34', 7500, 450.00, 'Monitor curvo ideal para productividad y gaming.', 'https://i.ibb.co/gZZCBvYg/A4.png'),
(gen_random_uuid(), 'Mouse Ergonómico Inalámbrico', 120, 25.99, 'Diseño vertical para reducir la fatiga de la muñeca.', 'https://i.ibb.co/tMj5nvBr/A9.png'),
(gen_random_uuid(), 'Auriculares Noise Cancelling', 350, 199.00, 'Cancelación activa de ruido y batería de 40 horas.', 'https://i.ibb.co/bRjTHkF1/A2.png'),
(gen_random_uuid(), 'Webcam 4K UltraHD', 200, 89.00, 'Cámara para streaming con enfoque automático y micrófono dual.', 'https://i.ibb.co/zh7F0HD6/A7.png'),
(gen_random_uuid(), 'Silla Gamer Omega', 18000, 299.50, 'Silla con soporte lumbar ajustable y reclinación 180 grados.', 'https://i.ibb.co/gZZCBvYg/A4.png'),
(gen_random_uuid(), 'Micrófono de Condensador', 600, 120.00, 'Ideal para podcasting y grabación de voces profesionales.', 'https://i.ibb.co/tMj5nvBr/A9.png'),
(gen_random_uuid(), 'Disco Duro Externo 2TB', 150, 65.00, 'Almacenamiento portátil USB 3.0 de alta velocidad.', 'https://i.ibb.co/bRjTHkF1/A2.png'),
(gen_random_uuid(), 'Memoria RAM 16GB DDR4', 50, 85.00, 'Módulo de memoria optimizado para alto rendimiento.', 'https://i.ibb.co/LX9hVZK9/A1.png'),
(gen_random_uuid(), 'Tarjeta Gráfica RTX 4070', 1200, 649.99, 'Potencia gráfica de última generación para gaming 4K.', 'https://i.ibb.co/tMj5nvBr/A9.png'),
(gen_random_uuid(), 'Procesador Octa-Core', 80, 320.00, 'Frecuencia de hasta 5.0GHz para tareas exigentes.', 'https://i.ibb.co/gZZCBvYg/A4.png'),
(gen_random_uuid(), 'Placa Base ATX Z790', 950, 210.00, 'Compatible con las últimas generaciones de procesadores.', 'https://i.ibb.co/zh7F0HD6/A7.png'),
(gen_random_uuid(), 'Fuente de Poder 750W Gold', 1500, 110.00, 'Certificación 80 Plus Gold para máxima eficiencia.', 'https://i.ibb.co/qLKfzMyd/A0.png'),
(gen_random_uuid(), 'Gabinete Mesh Airflow', 5000, 75.00, 'Excelente flujo de aire con paneles de malla frontal.', 'https://i.ibb.co/gZZCBvYg/A4.png'),
(gen_random_uuid(), 'Ventilador CPU Noctua', 700, 95.00, 'Enfriamiento silencioso y eficiente por aire.', 'https://i.ibb.co/gZZCBvYg/A4.png'),
(gen_random_uuid(), 'SSD NVMe 1TB Gen4', 15, 105.00, 'Velocidades de lectura hasta 7000MB/s.', 'https://i.ibb.co/tMj5nvBr/A9.png'),
(gen_random_uuid(), 'Hub USB-C 7 en 1', 100, 35.00, 'Adaptador con HDMI, SD y múltiples puertos USB.', 'https://i.ibb.co/LX9hVZK9/A1.png'),
(gen_random_uuid(), 'Tableta Digitalizadora', 450, 150.00, 'Perfecta para ilustradores y diseñadores gráficos.', 'https://i.ibb.co/bRjTHkF1/A2.png'),
(gen_random_uuid(), 'Altavoces Estéreo 2.0', 2500, 45.00, 'Sonido nítido para escritorio con conexión 3.5mm.', 'https://i.ibb.co/zh7F0HD6/A7.png'),
(gen_random_uuid(), 'Lámpara de Escritorio LED', 800, 29.00, 'Brazo flexible y ajuste de temperatura de color.', 'https://i.ibb.co/KczrctpM/A6.png'),
(gen_random_uuid(), 'Alfombrilla XXL Speed', 600, 19.50, 'Superficie de tela optimizada para sensores ópticos.', 'https://i.ibb.co/LztKGkG7/A3.png'),
(gen_random_uuid(), 'Router WiFi 6 Dual Band', 400, 130.00, 'Conexión estable y veloz para múltiples dispositivos.', 'https://i.ibb.co/qLKfzMyd/A0.png'),
(gen_random_uuid(), 'Repetidor de Señal Mesh', 200, 55.00, 'Extiende la cobertura de red en todo el hogar.', 'https://i.ibb.co/bRjTHkF1/A2.png'),
(gen_random_uuid(), 'Cargador Rápido GaN 65W', 150, 40.00, 'Cargador compacto para laptops y smartphones.', 'https://i.ibb.co/LX9hVZK9/A1.png'),
(gen_random_uuid(), 'Cable HDMI 2.1 Trenzado', 80, 15.00, 'Soporta resolución 8K a 60Hz.', 'https://i.ibb.co/tMj5nvBr/A9.png'),
(gen_random_uuid(), 'Soporte para Laptop', 500, 22.00, 'Aluminio resistente con altura regulable.', 'https://i.ibb.co/tMj5nvBr/A9.png'),
(gen_random_uuid(), 'Kit de Limpieza Pantallas', 250, 10.00, 'Líquido especial y paño de microfibra antiestático.', 'https://i.ibb.co/KczrctpM/A6.png'),
(gen_random_uuid(), 'Batería Externa 20000mAh', 400, 45.00, 'Carga múltiples dispositivos simultáneamente.', 'https://i.ibb.co/B2msPqL4/A5.png'),
(gen_random_uuid(), 'Teclado Numérico Externo', 100, 15.00, 'Ideal para laptops sin teclado extendido.', 'https://i.ibb.co/bRjTHkF1/A2.png'),
(gen_random_uuid(), 'Adaptador Bluetooth 5.0', 10, 12.00, 'Conecta periféricos inalámbricos a tu PC.', 'https://i.ibb.co/ym2FnggB/A8.png'),
(gen_random_uuid(), 'Joystick Arcade Retro', 1100, 85.00, 'Sensación clásica para juegos de lucha.', 'https://i.ibb.co/tMj5nvBr/A9.png'),
(gen_random_uuid(), 'Mando Wireless Pro', 210, 60.00, 'Compatible con PC, Consola y Android.', 'https://i.ibb.co/tMj5nvBr/A9.png'),
(gen_random_uuid(), 'Smartwatch Sport Fit', 50, 110.00, 'Monitor de ritmo cardíaco y GPS integrado.', 'https://i.ibb.co/B2msPqL4/A5.png'),
(gen_random_uuid(), 'Cámara de Seguridad IP', 300, 45.00, 'Visión nocturna y alertas al celular en tiempo real.', 'https://i.ibb.co/qLKfzMyd/A0.png'),
(gen_random_uuid(), 'Escáner Portátil de Documentos', 600, 95.00, 'Digitaliza tus archivos en cualquier lugar.', 'https://i.ibb.co/ym2FnggB/A8.png'),
(gen_random_uuid(), 'Impresora Inyección Tinta', 4000, 180.00, 'Sistema de tanques para bajo costo de impresión.', 'https://i.ibb.co/KczrctpM/A6.png'),
(gen_random_uuid(), 'Pack Papel Fotográfico', 300, 18.00, '20 hojas de alta calidad para impresoras.', 'https://i.ibb.co/LX9hVZK9/A1.png'),
(gen_random_uuid(), 'Trípode para Cámara', 1200, 40.00, 'Aluminio ligero con cabezal de tres vías.', 'https://i.ibb.co/tMj5nvBr/A9.png'),
(gen_random_uuid(), 'Anillo de Luz LED 10"', 400, 25.00, 'Ideal para videollamadas y creación de contenido.', 'https://i.ibb.co/LztKGkG7/A3.png'),
(gen_random_uuid(), 'Protector de Tensión 6 Tomas', 500, 20.00, 'Protege tus equipos de picos de voltaje.', 'https://i.ibb.co/zh7F0HD6/A7.png'),
(gen_random_uuid(), 'Tarjeta de Sonido Externa', 150, 30.00, 'Mejora la calidad de audio de tu computadora.', 'https://i.ibb.co/LztKGkG7/A3.png'),
(gen_random_uuid(), 'Capturadora de Video HDMI', 120, 160.00, 'Graba tus partidas en Full HD a 60fps.', 'https://i.ibb.co/B2msPqL4/A5.png'),
(gen_random_uuid(), 'Brazo Articulado Micrófono', 800, 35.00, 'Rotación completa y montaje en escritorio.', 'https://i.ibb.co/ym2FnggB/A8.png'),
(gen_random_uuid(), 'Panel Acústico Espuma', 100, 12.00, 'Set de paneles para reducir el eco ambiental.', 'https://i.ibb.co/KczrctpM/A6.png'),
(gen_random_uuid(), 'Organizador de Cables Clip', 50, 8.00, 'Mantiene tu escritorio ordenado y limpio.', 'https://i.ibb.co/qLKfzMyd/A0.png'),
(gen_random_uuid(), 'Maletín para Laptop 15.6', 700, 40.00, 'Protección acolchada y múltiples compartimentos.', 'https://i.ibb.co/LztKGkG7/A3.png'),
(gen_random_uuid(), 'Funda Protectora Tablet', 200, 15.00, 'Material resistente a caídas y rayones.', 'https://i.ibb.co/LX9hVZK9/A1.png'),
(gen_random_uuid(), 'Disco Sólido Externo 500GB', 100, 80.00, 'Velocidad SSD en formato de bolsillo.', 'https://i.ibb.co/B2msPqL4/A5.png'),
(gen_random_uuid(), 'Switch Gigabit 5 Puertos', 300, 22.00, 'Expande tu red cableada fácilmente.', 'https://i.ibb.co/tMj5nvBr/A9.png'),
(gen_random_uuid(), 'Soporte Monitor Pared', 1500, 30.00, 'Libera espacio en tu escritorio con este soporte VESA.', 'https://i.ibb.co/KczrctpM/A6.png');