DELETE FROM PRODUCTOS;
SELECT * FROM PRODUCTOS;
INSERT INTO PRODUCTOS (uuid, nombre, peso, precio, descripcion, url_imagen) VALUES
(gen_random_uuid(), 'Teclado Mecánico RGB', 850, 75.50, 'Teclado con switches blue y retroiluminación personalizada.', 'https://i.ibb.co/qLKfzMyd/A0.png'),
(gen_random_uuid(), 'Monitor UltraWide 34', 7500, 450.00, 'Monitor curvo ideal para productividad y gaming.', 'https://i.ibb.co/gZZCBvYg/A4.png'),
(gen_random_uuid(), 'Mouse Ergonómico Inalámbrico', 120, 25.99, 'Diseño vertical para reducir la fatiga de la muñeca.', 'https://i.ibb.co/tMj5nvBr/A9.png'),
(gen_random_uuid(), 'Auriculares Noise Cancelling', 350, 199.00, 'Cancelación activa de ruido y batería de 40 horas.', 'https://i.ibb.co/bRjTHkF1/A2.png'),
(gen_random_uuid(), 'Webcam 4K UltraHD', 200, 89.00, 'Cámara para streaming con enfoque automático y micrófono dual.', 'https://i.ibb.co/zh7F0HD6/A7.png'),
(gen_random_uuid(), 'Silla Gamer Omega', 18000, 299.50, 'Silla con soporte lumbar ajustable y reclinación 180 grados.', 'https://i.ibb.co/gZZCBvYg/A4.png'),
(gen_random_uuid(), 'Micrófono de Condensador', 600, 120.00, 'Ideal para podcasting y grabación de voces profesionales.', 'https://i.ibb.co/tMj5nvBr/A9.png'),
(gen_random_uuid(), 'Disco Duro Externo 2TB', 150, 65.00, 'Almacenamiento portátil USB 3.0 de alta velocidad.', 'https://i.ibb.co/bRjTHkF1/A2.png'),
(gen_random_uuid(), 'Memoria RAM 16GB DDR4', 50, 85.00, 'Módulo de memoria optimizado para alto rendimiento.', 'https://i.ibb.co/LX9hVZK9/A1.png'),
(gen_random_uuid(), 'Tarjeta Gráfica RTX 4070', 1200, 649.99, 'Potencia gráfica de última generación para gaming 4K.', 'https://i.ibb.co/tMj5nvBr/A9.png'),
(gen_random_uuid(), 'Procesador Octa-Core', 80, 320.00, 'Frecuencia de hasta 5.0GHz para tareas exigentes.', 'https://i.ibb.co/gZZCBvYg/A4.png'),
(gen_random_uuid(), 'Placa Base ATX Z790', 950, 210.00, 'Compatible con las últimas generaciones de procesadores.', 'https://i.ibb.co/zh7F0HD6/A7.png'),
(gen_random_uuid(), 'Fuente de Poder 750W Gold', 1500, 110.00, 'Certificación 80 Plus Gold para máxima eficiencia.', 'https://i.ibb.co/qLKfzMyd/A0.png'),
(gen_random_uuid(), 'Gabinete Mesh Airflow', 5000, 75.00, 'Excelente flujo de aire con paneles de malla frontal.', 'https://i.ibb.co/gZZCBvYg/A4.png'),
(gen_random_uuid(), 'Ventilador CPU Noctua', 700, 95.00, 'Enfriamiento silencioso y eficiente por aire.', 'https://i.ibb.co/gZZCBvYg/A4.png'),
(gen_random_uuid(), 'SSD NVMe 1TB Gen4', 15, 105.00, 'Velocidades de lectura hasta 7000MB/s.', 'https://i.ibb.co/tMj5nvBr/A9.png'),
(gen_random_uuid(), 'Hub USB-C 7 en 1', 100, 35.00, 'Adaptador con HDMI, SD y múltiples puertos USB.', 'https://i.ibb.co/LX9hVZK9/A1.png'),
(gen_random_uuid(), 'Tableta Digitalizadora', 450, 150.00, 'Perfecta para ilustradores y diseñadores gráficos.', 'https://i.ibb.co/bRjTHkF1/A2.png'),
(gen_random_uuid(), 'Altavoces Estéreo 2.0', 2500, 45.00, 'Sonido nítido para escritorio con conexión 3.5mm.', 'https://i.ibb.co/zh7F0HD6/A7.png'),
(gen_random_uuid(), 'Lámpara de Escritorio LED', 800, 29.00, 'Brazo flexible y ajuste de temperatura de color.', 'https://i.ibb.co/KczrctpM/A6.png'),
(gen_random_uuid(), 'Alfombrilla XXL Speed', 600, 19.50, 'Superficie de tela optimizada para sensores ópticos.', 'https://i.ibb.co/LztKGkG7/A3.png'),
(gen_random_uuid(), 'Router WiFi 6 Dual Band', 400, 130.00, 'Conexión estable y veloz para múltiples dispositivos.', 'https://i.ibb.co/qLKfzMyd/A0.png'),
(gen_random_uuid(), 'Repetidor de Señal Mesh', 200, 55.00, 'Extiende la cobertura de red en todo el hogar.', 'https://i.ibb.co/bRjTHkF1/A2.png'),
(gen_random_uuid(), 'Cargador Rápido GaN 65W', 150, 40.00, 'Cargador compacto para laptops y smartphones.', 'https://i.ibb.co/LX9hVZK9/A1.png'),
(gen_random_uuid(), 'Cable HDMI 2.1 Trenzado', 80, 15.00, 'Soporta resolución 8K a 60Hz.', 'https://i.ibb.co/tMj5nvBr/A9.png'),
(gen_random_uuid(), 'Soporte para Laptop', 500, 22.00, 'Aluminio resistente con altura regulable.', 'https://i.ibb.co/tMj5nvBr/A9.png'),
(gen_random_uuid(), 'Kit de Limpieza Pantallas', 250, 10.00, 'Líquido especial y paño de microfibra antiestático.', 'https://i.ibb.co/KczrctpM/A6.png'),
(gen_random_uuid(), 'Batería Externa 20000mAh', 400, 45.00, 'Carga múltiples dispositivos simultáneamente.', 'https://i.ibb.co/B2msPqL4/A5.png'),
(gen_random_uuid(), 'Teclado Numérico Externo', 100, 15.00, 'Ideal para laptops sin teclado extendido.', 'https://i.ibb.co/bRjTHkF1/A2.png'),
(gen_random_uuid(), 'Adaptador Bluetooth 5.0', 10, 12.00, 'Conecta periféricos inalámbricos a tu PC.', 'https://i.ibb.co/ym2FnggB/A8.png'),
(gen_random_uuid(), 'Joystick Arcade Retro', 1100, 85.00, 'Sensación clásica para juegos de lucha.', 'https://i.ibb.co/tMj5nvBr/A9.png'),
(gen_random_uuid(), 'Mando Wireless Pro', 210, 60.00, 'Compatible con PC, Consola y Android.', 'https://i.ibb.co/tMj5nvBr/A9.png'),
(gen_random_uuid(), 'Smartwatch Sport Fit', 50, 110.00, 'Monitor de ritmo cardíaco y GPS integrado.', 'https://i.ibb.co/B2msPqL4/A5.png'),
(gen_random_uuid(), 'Cámara de Seguridad IP', 300, 45.00, 'Visión nocturna y alertas al celular en tiempo real.', 'https://i.ibb.co/qLKfzMyd/A0.png'),
(gen_random_uuid(), 'Escáner Portátil de Documentos', 600, 95.00, 'Digitaliza tus archivos en cualquier lugar.', 'https://i.ibb.co/ym2FnggB/A8.png'),
(gen_random_uuid(), 'Impresora Inyección Tinta', 4000, 180.00, 'Sistema de tanques para bajo costo de impresión.', 'https://i.ibb.co/KczrctpM/A6.png'),
(gen_random_uuid(), 'Pack Papel Fotográfico', 300, 18.00, '20 hojas de alta calidad para impresoras.', 'https://i.ibb.co/LX9hVZK9/A1.png'),
(gen_random_uuid(), 'Trípode para Cámara', 1200, 40.00, 'Aluminio ligero con cabezal de tres vías.', 'https://i.ibb.co/tMj5nvBr/A9.png'),
(gen_random_uuid(), 'Anillo de Luz LED 10"', 400, 25.00, 'Ideal para videollamadas y creación de contenido.', 'https://i.ibb.co/LztKGkG7/A3.png'),
(gen_random_uuid(), 'Protector de Tensión 6 Tomas', 500, 20.00, 'Protege tus equipos de picos de voltaje.', 'https://i.ibb.co/zh7F0HD6/A7.png'),
(gen_random_uuid(), 'Tarjeta de Sonido Externa', 150, 30.00, 'Mejora la calidad de audio de tu computadora.', 'https://i.ibb.co/LztKGkG7/A3.png'),
(gen_random_uuid(), 'Capturadora de Video HDMI', 120, 160.00, 'Graba tus partidas en Full HD a 60fps.', 'https://i.ibb.co/B2msPqL4/A5.png'),
(gen_random_uuid(), 'Brazo Articulado Micrófono', 800, 35.00, 'Rotación completa y montaje en escritorio.', 'https://i.ibb.co/ym2FnggB/A8.png'),
(gen_random_uuid(), 'Panel Acústico Espuma', 100, 12.00, 'Set de paneles para reducir el eco ambiental.', 'https://i.ibb.co/KczrctpM/A6.png'),
(gen_random_uuid(), 'Organizador de Cables Clip', 50, 8.00, 'Mantiene tu escritorio ordenado y limpio.', 'https://i.ibb.co/qLKfzMyd/A0.png'),
(gen_random_uuid(), 'Maletín para Laptop 15.6', 700, 40.00, 'Protección acolchada y múltiples compartimentos.', 'https://i.ibb.co/LztKGkG7/A3.png'),
(gen_random_uuid(), 'Funda Protectora Tablet', 200, 15.00, 'Material resistente a caídas y rayones.', 'https://i.ibb.co/LX9hVZK9/A1.png'),
(gen_random_uuid(), 'Disco Sólido Externo 500GB', 100, 80.00, 'Velocidad SSD en formato de bolsillo.', 'https://i.ibb.co/B2msPqL4/A5.png'),
(gen_random_uuid(), 'Switch Gigabit 5 Puertos', 300, 22.00, 'Expande tu red cableada fácilmente.', 'https://i.ibb.co/tMj5nvBr/A9.png'),
(gen_random_uuid(), 'Soporte Monitor Pared', 1500, 30.00, 'Libera espacio en tu escritorio con este soporte VESA.', 'https://i.ibb.co/KczrctpM/A6.png'),
(gen_random_uuid(), 'Teclado Mecánico Mini 60%', 550, 65.00, 'Diseño compacto sin teclado numérico, ideal para gaming.', 'https://i.ibb.co/qLKfzMyd/A0.png'),
(gen_random_uuid(), 'Monitor Gaming 144Hz', 6200, 299.99, 'Resolución Full HD con tiempo de respuesta de 1ms.', 'https://i.ibb.co/gZZCBvYg/A4.png'),
(gen_random_uuid(), 'Mouse Pad RGB XL', 400, 35.00, 'Superficie de microfibra con bordes iluminados.', 'https://i.ibb.co/LztKGkG7/A3.png'),
(gen_random_uuid(), 'Auriculares Bluetooth Sport', 150, 45.90, 'Resistentes al sudor con ganchos para las orejas.', 'https://i.ibb.co/bRjTHkF1/A2.png'),
(gen_random_uuid(), 'Webcam 1080p Basic', 180, 45.00, 'Cámara web con micrófono integrado para videollamadas.', 'https://i.ibb.co/zh7F0HD6/A7.png'),
(gen_random_uuid(), 'Silla Gamer Pro Black', 19500, 350.00, 'Cuero sintético premium y apoyabrazos 4D.', 'https://i.ibb.co/gZZCBvYg/A4.png'),
(gen_random_uuid(), 'Micrófono Lavallier', 50, 25.00, 'Clip discreto para entrevistas y grabaciones con móvil.', 'https://i.ibb.co/tMj5nvBr/A9.png'),
(gen_random_uuid(), 'Disco Duro 4TB Red', 600, 115.00, 'Optimizado para sistemas NAS y almacenamiento masivo.', 'https://i.ibb.co/bRjTHkF1/A2.png'),
(gen_random_uuid(), 'Memoria RAM 32GB DDR5', 60, 180.00, 'Nueva generación de alta velocidad para multitarea.', 'https://i.ibb.co/LX9hVZK9/A1.png'),
(gen_random_uuid(), 'Tarjeta Gráfica RTX 4060', 1100, 320.00, 'Excelente rendimiento en 1080p con Ray Tracing.', 'https://i.ibb.co/tMj5nvBr/A9.png'),
(gen_random_uuid(), 'Procesador Hexa-Core', 75, 195.00, 'Rendimiento equilibrado para gaming y oficina.', 'https://i.ibb.co/gZZCBvYg/A4.png'),
(gen_random_uuid(), 'Placa Base Micro-ATX', 800, 120.00, 'Formato compacto para builds de tamaño medio.', 'https://i.ibb.co/zh7F0HD6/A7.png'),
(gen_random_uuid(), 'Fuente 600W Bronze', 1300, 65.00, 'Eficiencia energética básica pero fiable.', 'https://i.ibb.co/qLKfzMyd/A0.png'),
(gen_random_uuid(), 'Gabinete Mini Tower', 4000, 55.00, 'Estética minimalista blanca para setups limpios.', 'https://i.ibb.co/gZZCBvYg/A4.png'),
(gen_random_uuid(), 'Refrigeración Líquida 240mm', 1200, 89.00, 'Mantiene tu CPU fría bajo cargas intensas.', 'https://i.ibb.co/gZZCBvYg/A4.png'),
(gen_random_uuid(), 'SSD M.2 500GB', 12, 55.00, 'Arranque de Windows en pocos segundos.', 'https://i.ibb.co/tMj5nvBr/A9.png'),
(gen_random_uuid(), 'Adaptador USB-C a Ethernet', 50, 20.00, 'Conexión por cable para laptops ultradelgadas.', 'https://i.ibb.co/LX9hVZK9/A1.png'),
(gen_random_uuid(), 'Lápiz Óptico Digital', 30, 45.00, 'Sensible a la presión para dibujo natural.', 'https://i.ibb.co/bRjTHkF1/A2.png'),
(gen_random_uuid(), 'Barra de Sonido PC', 1500, 60.00, 'Se ajusta debajo del monitor para ahorrar espacio.', 'https://i.ibb.co/zh7F0HD6/A7.png'),
(gen_random_uuid(), 'Lámpara Monitor Screenbar', 450, 49.00, 'Ilumina tu escritorio sin reflejos en la pantalla.', 'https://i.ibb.co/KczrctpM/A6.png'),
(gen_random_uuid(), 'Alfombrilla de Cuero', 500, 25.00, 'Elegancia y precisión para el escritorio de oficina.', 'https://i.ibb.co/LztKGkG7/A3.png'),
(gen_random_uuid(), 'Router WiFi 5 Económico', 350, 40.00, 'Ideal para apartamentos pequeños.', 'https://i.ibb.co/qLKfzMyd/A0.png'),
(gen_random_uuid(), 'Switch Red 8 Puertos', 400, 30.00, 'Conecta toda tu oficina a la red local.', 'https://i.ibb.co/bRjTHkF1/A2.png'),
(gen_random_uuid(), 'Cargador Pared 20W USB-C', 80, 15.00, 'Carga rápida para dispositivos móviles.', 'https://i.ibb.co/LX9hVZK9/A1.png'),
(gen_random_uuid(), 'Cable DisplayPort 1.4', 90, 18.00, 'Soporta altas tasas de refresco en gaming.', 'https://i.ibb.co/tMj5nvBr/A9.png'),
(gen_random_uuid(), 'Base Enfriadora Laptop', 600, 28.00, 'Dos ventiladores potentes para evitar sobrecalentamiento.', 'https://i.ibb.co/tMj5nvBr/A9.png'),
(gen_random_uuid(), 'Aire Comprimido Limpieza', 300, 8.00, 'Remueve el polvo de lugares difíciles.', 'https://i.ibb.co/KczrctpM/A6.png'),
(gen_random_uuid(), 'Powerbank 10000mAh Slim', 220, 25.00, 'Cabe en tu bolsillo para carga de emergencia.', 'https://i.ibb.co/B2msPqL4/A5.png'),
(gen_random_uuid(), 'Teclado Bluetooth Multi-Sync', 400, 45.00, 'Cambia entre 3 dispositivos con un botón.', 'https://i.ibb.co/bRjTHkF1/A2.png'),
(gen_random_uuid(), 'Antena WiFi USB', 20, 15.00, 'Mejora la recepción inalámbrica de tu torre.', 'https://i.ibb.co/ym2FnggB/A8.png'),
(gen_random_uuid(), 'Mando Estilo Retro USB', 150, 20.00, 'Diseño clásico para emuladores de consola.', 'https://i.ibb.co/tMj5nvBr/A9.png'),
(gen_random_uuid(), 'Gamepad Móvil Clip', 100, 12.00, 'Sujeta tu smartphone para jugar con comodidad.', 'https://i.ibb.co/tMj5nvBr/A9.png'),
(gen_random_uuid(), 'Pulsera de Actividad Smart', 30, 29.00, 'Contador de pasos y notificaciones básicas.', 'https://i.ibb.co/B2msPqL4/A5.png'),
(gen_random_uuid(), 'Cámara Espía Oculta', 150, 55.00, 'Grabación discreta en resolución 720p.', 'https://i.ibb.co/qLKfzMyd/A0.png'),
(gen_random_uuid(), 'Escáner de Negativos', 900, 140.00, 'Convierte tus viejas fotos en archivos digitales.', 'https://i.ibb.co/ym2FnggB/A8.png'),
(gen_random_uuid(), 'Impresora Láser Monocromo', 6000, 150.00, 'Impresión rápida y económica de solo texto.', 'https://i.ibb.co/KczrctpM/A6.png'),
(gen_random_uuid(), 'Tóner Negro Compatible', 500, 35.00, 'Repuesto de larga duración para impresoras láser.', 'https://i.ibb.co/LX9hVZK9/A1.png'),
(gen_random_uuid(), 'Monopié de Viaje', 500, 30.00, 'Estabilidad para fotografía en espacios reducidos.', 'https://i.ibb.co/tMj5nvBr/A9.png'),
(gen_random_uuid(), 'Softbox Kit Fotografía', 3000, 85.00, 'Iluminación suave para retratos y productos.', 'https://i.ibb.co/LztKGkG7/A3.png'),
(gen_random_uuid(), 'Regleta Inteligente WiFi', 450, 38.00, 'Controla cada toma desde tu smartphone.', 'https://i.ibb.co/zh7F0HD6/A7.png'),
(gen_random_uuid(), 'DAC de Audio Portátil', 50, 50.00, 'Conversor digital-analógico para audiófilos.', 'https://i.ibb.co/LztKGkG7/A3.png'),
(gen_random_uuid(), 'Capturadora 4K Externa', 200, 199.00, 'Streaming profesional para consolas next-gen.', 'https://i.ibb.co/B2msPqL4/A5.png'),
(gen_random_uuid(), 'Filtro Antipop Micrófono', 200, 15.00, 'Elimina los ruidos de aire al hablar.', 'https://i.ibb.co/ym2FnggB/A8.png'),
(gen_random_uuid(), 'Trampa de Bajos Acústica', 500, 45.00, 'Mejora la acústica en las esquinas de tu estudio.', 'https://i.ibb.co/KczrctpM/A6.png'),
(gen_random_uuid(), 'Brida de Velcro Roll', 100, 10.00, 'Rollo de 5 metros para gestión personalizada de cables.', 'https://i.ibb.co/qLKfzMyd/A0.png'),
(gen_random_uuid(), 'Mochila Antirrobo Laptop', 1100, 55.00, 'Diseño con cremalleras ocultas y puerto USB.', 'https://i.ibb.co/LztKGkG7/A3.png'),
(gen_random_uuid(), 'Funda de Silicona Tablet', 150, 12.00, 'Protección suave y antideslizante.', 'https://i.ibb.co/LX9hVZK9/A1.png'),
(gen_random_uuid(), 'SSD SATA III 2TB', 80, 140.00, 'Gran capacidad para almacenamiento interno.', 'https://i.ibb.co/B2msPqL4/A5.png'),
(gen_random_uuid(), 'Adaptador PLC Powerline', 600, 75.00, 'Lleva internet a través de la red eléctrica.', 'https://i.ibb.co/tMj5nvBr/A9.png'),
(gen_random_uuid(), 'Soporte Monitor Doble', 3500, 65.00, 'Brazos articulados para dos pantallas de 27".', 'https://i.ibb.co/KczrctpM/A6.png'),
(gen_random_uuid(), 'Teclado para Smart TV', 300, 32.00, 'Con touchpad integrado para navegar desde el sofá.', 'https://i.ibb.co/qLKfzMyd/A0.png'),
(gen_random_uuid(), 'Monitor Portátil 15"', 900, 180.00, 'Segunda pantalla USB-C para trabajar en viajes.', 'https://i.ibb.co/gZZCBvYg/A4.png'),
(gen_random_uuid(), 'Ratón Gaming Ultra-ligero', 60, 55.00, 'Carcasa perforada para reducir peso a 60g.', 'https://i.ibb.co/tMj5nvBr/A9.png'),
(gen_random_uuid(), 'Auriculares de Estudio', 300, 110.00, 'Respuesta de frecuencia plana para mezcla de audio.', 'https://i.ibb.co/bRjTHkF1/A2.png'),
(gen_random_uuid(), 'Webcam con Tapa Privacidad', 190, 50.00, 'Obturador físico para mayor seguridad.', 'https://i.ibb.co/zh7F0HD6/A7.png'),
(gen_random_uuid(), 'Silla Gamer Edición Tela', 19000, 310.00, 'Tejido transpirable ideal para climas cálidos.', 'https://i.ibb.co/gZZCBvYg/A4.png'),
(gen_random_uuid(), 'Micrófono Dinámico XLR', 750, 95.00, 'Perfecto para evitar ruidos de fondo en streaming.', 'https://i.ibb.co/tMj5nvBr/A9.png'),
(gen_random_uuid(), 'Disco Duro 10TB Heliox', 800, 280.00, 'Máxima capacidad para servidores de archivos.', 'https://i.ibb.co/bRjTHkF1/A2.png'),
(gen_random_uuid(), 'Memoria RAM Laptop 8GB', 30, 40.00, 'Módulo SODIMM para actualizar tu portátil.', 'https://i.ibb.co/LX9hVZK9/A1.png'),
(gen_random_uuid(), 'Tarjeta Gráfica RTX 4080', 1600, 1199.00, 'Rendimiento extremo para entusiastas.', 'https://i.ibb.co/tMj5nvBr/A9.png'),
(gen_random_uuid(), 'Procesador Low Power', 65, 140.00, 'Eficiente para HTPC y bajo consumo.', 'https://i.ibb.co/gZZCBvYg/A4.png'),
(gen_random_uuid(), 'Placa Base Gamer WiFi', 1100, 250.00, 'Incluye Bluetooth y antenas externas.', 'https://i.ibb.co/zh7F0HD6/A7.png'),
(gen_random_uuid(), 'Fuente 1000W Platinum', 2200, 240.00, 'Máxima eficiencia para equipos de gama alta.', 'https://i.ibb.co/qLKfzMyd/A0.png'),
(gen_random_uuid(), 'Gabinete Full Tower XL', 8500, 180.00, 'Espacio de sobra para refrigeración líquida triple.', 'https://i.ibb.co/gZZCBvYg/A4.png'),
(gen_random_uuid(), 'Pasta Térmica Premium', 10, 12.00, 'Alta conductividad para mejorar temperaturas de CPU.', 'https://i.ibb.co/gZZCBvYg/A4.png'),
(gen_random_uuid(), 'SSD NVMe 2TB Gen5', 20, 290.00, 'La velocidad más rápida disponible comercialmente.', 'https://i.ibb.co/tMj5nvBr/A9.png'),
(gen_random_uuid(), 'Lector Tarjetas SD USB 3', 40, 15.00, 'Transfiere tus fotos rápidamente a la PC.', 'https://i.ibb.co/LX9hVZK9/A1.png'),
(gen_random_uuid(), 'Guante Dibujo Digital', 15, 8.00, 'Evita manchas y fricción en la tableta gráfica.', 'https://i.ibb.co/bRjTHkF1/A2.png'),
(gen_random_uuid(), 'Subwoofer Activo 10"', 8000, 199.00, 'Bajos profundos para tu sistema de sonido.', 'https://i.ibb.co/zh7F0HD6/A7.png'),
(gen_random_uuid(), 'Control Remoto PC', 120, 22.00, 'Navega por el media center con facilidad.', 'https://i.ibb.co/KczrctpM/A6.png'),
(gen_random_uuid(), 'Alfombrilla Circular', 200, 15.00, 'Forma original para espacios pequeños.', 'https://i.ibb.co/LztKGkG7/A3.png'),
(gen_random_uuid(), 'Router Industrial VPN', 1200, 450.00, 'Seguridad avanzada para empresas.', 'https://i.ibb.co/qLKfzMyd/A0.png'),
(gen_random_uuid(), 'Inyector PoE+', 250, 35.00, 'Alimenta cámaras IP por el cable de red.', 'https://i.ibb.co/bRjTHkF1/A2.png'),
(gen_random_uuid(), 'Cargador Coche 30W', 60, 18.00, 'Dos puertos USB para viajes largos.', 'https://i.ibb.co/LX9hVZK9/A1.png'),
(gen_random_uuid(), 'Cable de Red CAT7 10m', 400, 22.00, 'Blindaje superior para evitar interferencias.', 'https://i.ibb.co/tMj5nvBr/A9.png'),
(gen_random_uuid(), 'Stand Auriculares Madera', 300, 35.00, 'Base elegante para lucir tus cascos.', 'https://i.ibb.co/tMj5nvBr/A9.png'),
(gen_random_uuid(), 'Kit Destornilladores Precisión', 450, 25.00, '64 puntas para reparar cualquier gadget.', 'https://i.ibb.co/KczrctpM/A6.png'),
(gen_random_uuid(), 'Cargador Solar Portátil', 500, 45.00, 'Carga tus equipos usando energía del sol.', 'https://i.ibb.co/B2msPqL4/A5.png'),
(gen_random_uuid(), 'Teclado Láser Proyectado', 150, 60.00, 'Proyecta un teclado funcional en cualquier mesa.', 'https://i.ibb.co/bRjTHkF1/A2.png'),
(gen_random_uuid(), 'Receptor Bluetooth Audio', 40, 20.00, 'Convierte tu equipo antiguo en inalámbrico.', 'https://i.ibb.co/ym2FnggB/A8.png'),
(gen_random_uuid(), 'Joystick de Vuelo HOTAS', 2500, 150.00, 'Inmersión total para simuladores de vuelo.', 'https://i.ibb.co/tMj5nvBr/A9.png'),
(gen_random_uuid(), 'Adaptador Mandos Consola', 50, 25.00, 'Usa mandos de Xbox en tu Playstation.', 'https://i.ibb.co/tMj5nvBr/A9.png'),
(gen_random_uuid(), 'Smart Tag Localizador', 15, 29.00, 'No pierdas nunca más tus llaves o mochila.', 'https://i.ibb.co/B2msPqL4/A5.png'),
(gen_random_uuid(), 'Monitor de Bebés WiFi', 400, 75.00, 'Audio bidireccional y sensor de temperatura.', 'https://i.ibb.co/qLKfzMyd/A0.png'),
(gen_random_uuid(), 'Escáner de Código Barras', 350, 45.00, 'Lector láser para puntos de venta.', 'https://i.ibb.co/ym2FnggB/A8.png'),
(gen_random_uuid(), 'Multifuncional Color WiFi', 5500, 130.00, 'Escanea, copia e imprime sin cables.', 'https://i.ibb.co/KczrctpM/A6.png'),
(gen_random_uuid(), 'Cartucho Tinta XL Color', 100, 45.00, 'Mayor rendimiento de páginas impresas.', 'https://i.ibb.co/LX9hVZK9/A1.png'),
(gen_random_uuid(), 'Estabilizador de Móvil (Gimbal)', 450, 89.00, 'Videos fluidos y sin vibraciones con tu celular.', 'https://i.ibb.co/tMj5nvBr/A9.png'),
(gen_random_uuid(), 'Fondo Croma Verde', 2000, 40.00, 'Tela para efectos visuales en streaming.', 'https://i.ibb.co/LztKGkG7/A3.png'),
(gen_random_uuid(), 'SAI / UPS 1500VA', 12000, 180.00, 'Respaldo de batería para apagones inesperados.', 'https://i.ibb.co/zh7F0HD6/A7.png'),
(gen_random_uuid(), 'Tarjeta Sonido PCIe 7.1', 200, 85.00, 'Sonido envolvente real para tu PC de escritorio.', 'https://i.ibb.co/LztKGkG7/A3.png'),
(gen_random_uuid(), 'Encoder HDMI para Stream', 300, 250.00, 'Transmite directamente sin necesidad de PC.', 'https://i.ibb.co/B2msPqL4/A5.png'),
(gen_random_uuid(), 'Soporte Micro Suspensión', 150, 20.00, 'Evita vibraciones mecánicas en el micrófono.', 'https://i.ibb.co/ym2FnggB/A8.png'),
(gen_random_uuid(), 'Cortina Acústica Pesada', 4000, 65.00, 'Bloquea el ruido exterior de las ventanas.', 'https://i.ibb.co/KczrctpM/A6.png'),
(gen_random_uuid(), 'Gestor de Cables Espiral', 150, 12.00, 'Tubo flexible para agrupar cables sueltos.', 'https://i.ibb.co/qLKfzMyd/A0.png'),
(gen_random_uuid(), 'Maleta Rígida Cámara', 2500, 110.00, 'Protección extrema contra golpes y agua.', 'https://i.ibb.co/LztKGkG7/A3.png'),
(gen_random_uuid(), 'Lápiz Limpiador Lentes', 20, 10.00, 'Punta de carbono para quitar huellas de ópticas.', 'https://i.ibb.co/LX9hVZK9/A1.png'),
(gen_random_uuid(), 'Docking Station Triple 4K', 600, 160.00, 'Convierte tu laptop en una estación potente.', 'https://i.ibb.co/B2msPqL4/A5.png'),
(gen_random_uuid(), 'Inyector WiFi USB High Gain', 100, 30.00, 'Antena de largo alcance para redes lejanas.', 'https://i.ibb.co/tMj5nvBr/A9.png'),
(gen_random_uuid(), 'Soporte CPU con Ruedas', 1200, 18.00, 'Mueve tu torre fácilmente para limpiar.', 'https://i.ibb.co/KczrctpM/A6.png');